import { describe, it, expect } from "vitest";
import { mkdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import {
  SchematicDocument,
  parseSchematicDocument,
  type SchematicSymbolNode,
  type TitleBlockNode,
} from "../src/document/SchematicDocument.js";

const TEMPLATE = join(import.meta.dirname, "..", "template.kicad_sch");
const OUT_DIR = join(import.meta.dirname, "..", "test-output");

describe("SchematicDocument", () => {
  it("parses typed top-level nodes from an existing schematic", () => {
    const text = readFileSync(TEMPLATE, "utf-8");
    const parsed = parseSchematicDocument(text);

    expect(parsed.nodes.some(node => node.kind === "title_block")).toBe(true);
    expect(parsed.nodes.filter((node): node is SchematicSymbolNode => node.kind === "symbol")).toHaveLength(4);

    const titleBlock = parsed.nodes.find((node): node is TitleBlockNode => node.kind === "title_block");
    expect(titleBlock?.title).toBe("LED Resistor Test Circuit");

    const resistor = parsed.nodes.find(
      (node): node is SchematicSymbolNode => node.kind === "symbol" && node.ref === "R1"
    );
    expect(resistor?.libraryId).toBe("Device:R");
    expect(resistor?.value).toBe("330");
  });

  it("round-trips an unchanged schematic byte-for-byte", () => {
    const text = readFileSync(TEMPLATE, "utf-8");
    const doc = SchematicDocument.parse(text);

    expect(doc.isDirty).toBe(false);
    expect(doc.toString()).toBe(text);
  });

  it("supports dirty tracking and source-preserving saveAs for title block edits", () => {
    mkdirSync(OUT_DIR, { recursive: true });

    const doc = SchematicDocument.open(TEMPLATE);
    expect(doc.isDirty).toBe(false);

    doc.setTitle("Updated Title");
    doc.setDate("2026-04-11");
    expect(doc.isDirty).toBe(true);
    expect(doc.titleBlock.title).toBe("Updated Title");
    expect(doc.titleBlock.date).toBe("2026-04-11");

    const outPath = join(OUT_DIR, "schematic-document-saveas.kicad_sch");
    doc.saveAs(outPath);

    expect(doc.path).toBe(outPath);
    expect(doc.isDirty).toBe(false);

    const saved = readFileSync(outPath, "utf-8");
    expect(saved).toContain('(title "Updated Title")');
    expect(saved).toContain('(date "2026-04-11")');
  });

  it("preserves existing title block comments when editing known fields", () => {
    mkdirSync(OUT_DIR, { recursive: true });

    const doc = SchematicDocument.open(TEMPLATE);
    doc.setTitle("Preserved Comments");

    const outPath = join(OUT_DIR, "schematic-document-title-comments.kicad_sch");
    doc.saveAs(outPath);

    const saved = readFileSync(outPath, "utf-8");
    expect(saved).toContain('(title "Preserved Comments")');
    expect(saved).toContain('(comment 1 "Generated by schematic-agent")');
  });

  it("reloads an opened document from disk", () => {
    mkdirSync(OUT_DIR, { recursive: true });

    const outPath = join(OUT_DIR, "schematic-document-reload.kicad_sch");
    writeFileSync(outPath, readFileSync(TEMPLATE, "utf-8"), "utf-8");

    const doc = SchematicDocument.open(outPath);
    expect(doc.titleBlock.title).toBe("LED Resistor Test Circuit");

    const updated = readFileSync(TEMPLATE, "utf-8").replace(
      'LED Resistor Test Circuit',
      'Reloaded Title Block',
    );
    writeFileSync(outPath, updated, "utf-8");

    doc.reload();
    expect(doc.isDirty).toBe(false);
    expect(doc.titleBlock.title).toBe("Reloaded Title Block");
  });

  it("preserves unknown top-level nodes on round-trip", () => {
    const text = `(kicad_sch
\t(version 20250114)
\t(generator "test")
\t(mystery_block
\t\t(foo "bar")
\t)
\t(embedded_fonts no)
)
`;
    const doc = SchematicDocument.parse(text);
    expect(doc.toString()).toBe(text);
  });
});
